version: "3"
services:
##########################
#Setup node container
##########################
  frontend:
    build: ./FrontEnd/Hello-World-Tester/hello-world-tester    
    environment:
      REACT_APP_SIMULATOR_HOST: backend:8080
      APP_SERVER_PORT: 3000
    ports:
      - 3000:80
   # command: npm start
##########################
#Setup API container
##########################
  backend: 
    build: ./BackEnd/Hello-World-API
    ports:
     - 8080:8080

