version: "3"
services:
##########################
#Setup node container
##########################
  frontend:
    build: ./FrontEnd/Hello-World-Tester/hello-world-tester
    expose: 
      - 3000
    environment:
      API_HOST: localhost:8080
      APP_SERVER_PORT: 3000
    ports:
      - 3000:3000
   # command: npm start
##########################
#Setup API container
##########################
  backend: 
    build: ./BackEnd\Hello-World-API
    expose:
     - 8080
    ports:
     - 8080:8080

